### ISSUE TITLE
builds failing due to ccache problems

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/buildfarm_deployment#113]
See:
* http://build.ros.org/job/Ibin_uT32__ecto_ros__ubuntu_trusty_i386__binary/3/consoleFull
* http://build.ros.org/job/Ibin_uT64__opt_camera__ubuntu_trusty_amd64__binary/3/consoleFull
* http://build.ros.org/job/Ibin_uT64__swri_image_util__ubuntu_trusty_amd64__binary/3/consoleFull
* http://build.ros.org/job/Ibin_uT64__zbar_ros__ubuntu_trusty_amd64__binary/3/consoleFull

I did some research and the following ticket seems to describe our problem: https://code.google.com/p/chromium/issues/detail?id=411984
The following fix went into ccache: https://git.samba.org/?p=ccache.git;a=commit;h=a07f46a3b0f7e452d50690b831bb4c99fbc6650f
But that is not part of the CCache version shipped in Trusty: http://packages.ubuntu.com/trusty/ccache http://changelogs.ubuntu.com/changelogs/pool/main/c/ccache/ccache_3.1.9-1/changelog

I think we need a newer version of CCache (3.2+, e.g. from Wily or Xenial).

**Comment by tfoote** [comment]
This has been an ongoing issue: https://github.com/ros-infrastructure/buildfarm/issues/174

**Comment by dirk-thomas** [comment]
While the symptom was known for a while it is only now that we are aware of a way to fix the problem. So we should try to deploy a newer version of CCache to confirm that it fixes the problem.

**Comment by tfoote** [comment]
Yes, we should find a way to back port the fix. I just wanted to connect it to the old ticket.

**Comment by dirk-thomas** [comment]
http://build.ros.org/job/Jbin_arm_uThf__object_recognition_tabletop__ubuntu_trusty_armhf__binary/6/console

**Comment by dirk-thomas** [comment]
http://build.ros.org/job/Jbin_uU32__jsk_perception__ubuntu_utopic_i386__binary/5/console

**Comment by dirk-thomas** [comment]
http://build.ros.org/job/Ibin_uS64__jsk_rviz_plugins__ubuntu_saucy_amd64__binary/6/console

**Comment by dirk-thomas** [comment]
http://build.ros.org/job/Jbin_uT32__nerian_sp1__ubuntu_trusty_i386__binary/5/console
