### ISSUE TITLE
parameterize and increase squid disk cache size

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/buildfarm_deployment#114]
We're easily filling it and it's rolling over at 5G

**Comment by dirk-thomas** [comment]
Without an increased cache some jobs fail since pulling large Debian packages takes too long: http://build.ros.org/job/Idoc__zbar_ros__ubuntu_trusty_amd64/8/console

**Comment by tfoote** [comment]
The cache might help mask this problem. but it shouldn't take over an hour to download 716 MB of data as it does in that job even without the cache at all. 

It does look like the same packages are at issue here. Aka `texlive-latex-extra-doc` which is the same large deb that we've seen issues with before.
```
00:42:09.325 Get:128 http://archive.ubuntu.com/ubuntu/ trusty/main texlive-pictures all 2013.20140215-1 [2,414 kB]
00:42:33.383 Get:129 http://archive.ubuntu.com/ubuntu/ trusty/main texlive-latex-extra all 2013.20140215-2 [7,286 kB]
00:43:50.637 Get:130 http://archive.ubuntu.com/ubuntu/ trusty/main texlive-latex-extra-doc all 2013.20140215-2 [317 MB]
01:38:46.539 Get:131 http://archive.ubuntu.com/ubuntu/ trusty/main texlive-latex-recommended-doc all 2013.20140215-1 [35.0 MB]
01:45:07.552 Get:132 http://archive.ubuntu.com/ubuntu/ trusty/main texlive-luatex all 2013.20140215-1 [8,204 kB]
```

**Comment by dirk-thomas** [comment]
Are these configuration options documented anywhere?

**Comment by tfoote** [comment]
I added commented values in the slave config: https://github.com/ros-infrastructure/buildfarm_deployment_config/blob/master/slave/common.yaml#L24-L25

**Comment by dirk-thomas** [comment]
The comment doesn't mention yet what those values do, what their unit is, etc.
