### ISSUE TITLE
ubuntu xenial support

### ISSUE THREAD

**Issue by mistoll** [ros-infrastructure/buildfarm_deployment#137]
On ubuntu xenial there are some issues:

**Ruby 1.9 is not available**
This can easily be solved using a ruby version manager like "rvm". 
While upgrading to ruby 2+ would have a large impact (e.g. puppet 4.0)

**docker version tag**
Docker uses the distribution in its version string (1.9.1-0~trusty).
On xenial the minimum docker version available is 1.11.0.

**upstart vs. systemd** 
Xenial uses systemd as init service. This causes some issues

There're almoust 3 years left till trusty eol. Are there any plans to support xenial?

**Comment by tfoote** [comment]
We're likely going to be looking into switching to xenial soon. Though when we switch we will likely drop support for trusty.

**Comment by mistoll** [comment]
Dropping trusty support will definitively ease things. And supporting both, trusty and xenial does not make much sense to me. Anybody, still running a trusty buildfarm, can easily use the trusty branch.

**Comment by nuclearsandwich** [comment]
@mistoll there is a legacy `trusty` branch that we are no longer actively maintaining but master now targets xenial and has received a significant refactor.
