### ISSUE TITLE
Platform spec missing

### ISSUE THREAD

**Issue by alex-gee** [ros-infrastructure/buildfarm_deployment#150]
Hi! Maybe I just miss an important point, but I don't get on what platforms it is supposed to work. Is it Ubuntu 14.04? Or 12.04. Thanks for clarification!

**Comment by nuclearsandwich** [comment]
The master branch currently targets 14.04 (trusty) and I don't believe (but haven't confirmed) that this code ever supported 12.04. The initial commit is from September 2014 so I'd bet that it was built for Trusty.

**Comment by alex-gee** [comment]
Ok thx for the clarification!
