### ISSUE TITLE
Docs should more clearly warn this only works on 14.04 image

### ISSUE THREAD

**Issue by jgoppert** [ros-infrastructure/buildfarm_deployment#151]
I setup all of my images only to realize I had to do it all over again when ruby-1.9-dev wasn't on 16.04.

**Comment by nuclearsandwich** [comment]
Thanks for the feedback. This is something that's come up more than once recently and so it's good to make it explicit. 

I've created a PR (#152) to add the currently supported server distribution to the readme. 

In case you prefer to stick with xenial, there's also [a branch on my fork](https://github.com/nuclearsandwich/buildfarm_deployment/tree/xenialize) that targets 16.04 (xenial) and a corresponding [config repo](https://github.com/nuclearsandwich/bf_config_experiments/tree/xenialize) that will become the basis for a migration to xenial for build.ros.org in the next several weeks. But it has not yet completed a QA pass and is currently only being used in a test environment for ROS 2.

**Comment by jgoppert** [comment]
@nuclearsandwich I appreciate the fix. Where best to ask for advice on setting up the buildfarm? I tacked onto the thread here: http://answers.ros.org/question/228446/failed-to-fetch-from-local-buildfarm-repo/?answer=263795#post-id-263795  I'm running into the same issue with reprepro not getting setup properly.

**Comment by tfoote** [comment]
@jgoppert You can ask your own questions on answers.ros.org and there's a category for the buildfarm on Discourse: https://discourse.ros.org/c/buildfarm

**Comment by jgoppert** [comment]
@tfoote Thanks.
