### ISSUE TITLE
reprepro removing dependencies is going much slower

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/buildfarm_deployment#165]
reprepro removefilter is much slower now.

---
From another thread 

It looks like the new version of reprepro underneath import_upstream is doing a few more things I pulled the console outputs and diffed with some notes here: https://gist.github.com/tfoote/63ef7af733c1c25be5d674369ef0220a

![image](https://user-images.githubusercontent.com/447804/31299402-14f5b978-aaa3-11e7-8620-85a81279f4cd.png)

Also the entry point into the subprocess call seems to go slower and the calculating packages to get is slower for each instance.

---

As well as it looks like import_package goes much slower when invalidating packages. It takes approximately 1 second per instance of removefilter
Invalidating an rqt_bag run took 29 seconds and invoked removefilter 24 times

![rqt_bag_import_time](https://user-images.githubusercontent.com/447804/32354437-ecf366ba-bfe6-11e7-824c-57bffe0879f2.png)

![image](https://user-images.githubusercontent.com/447804/32354507-3a134a82-bfe7-11e7-9f82-9e9b5ffa1a0f.png)

Invalidating cpp_common took 25 minutes and ran removefilter 1361 times. 

![cpp_common_import_time](https://user-images.githubusercontent.com/447804/32354429-e7bc8bb8-bfe6-11e7-9494-efcf4f003d01.png)

![image](https://user-images.githubusercontent.com/447804/32354531-51fbbf12-bfe7-11e7-85ca-f050d37d7c6a.png)

A typical near leaf package takes 2-3 seconds.

Looking at the machine while this job is running. The load average is ~1 but there's minimal CPU, Memory or Disk IO going on. I'm not sure what's blocking the process. This used to go much faster.

Here are a few metrics.

One outlier is that NewRelic is reporting that we're using 20GB of ram??

![repo_disk_usage](https://user-images.githubusercontent.com/447804/32354615-b718b2d8-bfe7-11e7-9131-c002f4b7070f.png)
![repo_metrics](https://user-images.githubusercontent.com/447804/32354616-b72f3030-bfe7-11e7-82a2-f5aa78f0cccd.png)
![repositories_20g](https://user-images.githubusercontent.com/447804/32354617-b741e0e0-bfe7-11e7-8bb2-0e56f2175397.png)

**Comment by tfoote** [comment]
Looking at the hosting it has 1800/3000 IOPS available. We could get a little bit more throughput, but from the stats it's not looking like IO is the limiting factor.

**Comment by nuclearsandwich** [comment]
Yesterday I took a look at the debian package built by https://github.com/ros-infrastructure/buildfarm_deployment/blob/master/dependencies/deb/build-reprepro.sh and the binary deb from zesty that @mikaelarguedas had deployed on the Trusty farm. I couldn't identify much in the way of substantive differences, certainly no source differences, which is to be expected since the debian package built by our script comes from the source package associated with the zesty binary package.

We could decide to deploy the zesty binary deb directly and see if that affects the reprepro behavior and startup times.

Beyond that the other mitigation discussed with @tfoote is to consolidate the removefilter invocations rather than running it once per package.

**Comment by nuclearsandwich** [comment]
Changes meant to address this issue are deployed and working smoothly. Since we haven't rebuilt from a low-level package yet we don't know for certain that this is resolved or have exact timing information from the production farm.

**Comment by nuclearsandwich** [comment]
Got a relatively large sample from production. http://build.ros.org/job/Krel_import-package/258995/ (that link will 404 pretty quickly as the import package jobs fall off the cliff but output is archived here: https://gist.github.com/nuclearsandwich/a8f5be14bbc203fd38e8b80cf638ee94

Total build time is 3.8 seconds to invalidate 515 packages which is just 1.5 seconds above our new mode of 2.3seconds. Again, we no longer have concrete data for how long comparable jobs used to take but as long as the performance holds, and I have no reason to expect it to degrade, this should prevent the severe bogging down and timeouts that we were seeing when low-level packages were importing.
