### ISSUE TITLE
"Proxy setup broken" after master deployment

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/buildfarm_deployment#212]
After a successful deployment of a master instance, Jenkins complains that: `It appears that your reverse proxy set up is broken`.

This is on an Ubuntu 16.04 `amd64` VM with a default Ubuntu Server install, working DNS and public hostnames. Both pre- and post-jep-200 version of `buildfarm_deployment`.

**Comment by gavanderhoorn** [comment]
@RonaldEnsing: FYI.

**Comment by gavanderhoorn** [comment]
The [Jenkins says my reverse proxy setup is broken](https://wiki.jenkins.io/display/JENKINS/Jenkins+says+my+reverse+proxy+setup+is+broken) page discusses this and provides some hints on what to check / how to address this. The last post (by Gary Phillip) helped.

For this particular host, I had to add the following settings to `/etc/apache2/sites-available25-master.conf`:

```
AllowEncodedSlashes NoDecode
```

and append `nocanon` to `ProxyPass / http://localhost:8080/`.

I've also:

 - updated `ServerName` from `master` to the actual hostname of the server
 - set `ProxyPreserveHost` to `On`

@nuclearsandwich: the proxy warning has popped up on all deployments for me, would it be an idea to add this to the Apache setup in [modules/profile/manifests/jenkins/master.pp](https://github.com/ros-infrastructure/buildfarm_deployment/blob/eb797fcc79317b298b474422c73960a542fe7f8a/modules/profile/manifests/jenkins/master.pp#L222-L228)?

**Comment by nuclearsandwich** [comment]
> @nuclearsandwich: the proxy warning has popped up on all deployments for me, would it be an idea to add this to the Apache setup in [modules/profile/manifests/jenkins/master.pp](https://github.com/ros-infrastructure/buildfarm_deployment/blob/eb797fcc79317b298b474422c73960a542fe7f8a/modules/profile/manifests/jenkins/master.pp#L222-L228)?

Yeah this has been present on all deployments (including the original Trusty canonical buildfarm) and because it never interfered with operation I let it be. But if there's a way to resolve the error message while still being flexible enough to work without too much manual config, I would merrily review the PR.

**Comment by gavanderhoorn** [comment]
> because it never interfered with operation I let it be

yes, it doesn't seem to really impact operations, but a warning/error is a warning/error, and I've noticed people wondering whether something is really broken.

I'll submit a PR.

**Comment by nuclearsandwich** [comment]
Resolved by @gavanderhoorn in #215. Thanks!
