### ISSUE TITLE
allow sending notification emails from Jenkins jobs

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/buildfarm_deployment#34]
Please also deploy and test this on the current test farm.

**Comment by tfoote** [comment]
installing postfix as an "internet site" has been tested. It looks like there's a popular puppet module we can use for installing it: https://forge.puppetlabs.com/thias/postfix

**Comment by tfoote** [comment]
postfix was getting flagged as spam a lot. I've changed it to use an authenticated smtp for better spam avoidance. It also requires setting the admin email in the locations settings.

**Comment by tfoote** [comment]
Reopening to track OSUOSL setting up our keys

**Comment by tfoote** [comment]
OSUOSL has added the SPF records such that we get SFP pass
