### ISSUE TITLE
docker cleanup script still interfering with builds

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/buildfarm_deployment#43]
The following build failed: http://54.183.26.131:8080/job/Ibin_uT32__rtmbuild__ubuntu_trusty_i386__binary/3/console

The excerpt from the build console:

    14:14:47 Step 23 : RUN echo "ros-indigo-message-generation: 0.2.10-0trusty" && python3 -u /tmp/wrapper_scripts/apt-get.py update-and-install -q -y ros-indigo-message-generation
    14:14:47  ---> Running in 6391121c452d
    14:14:48 ros-indigo-message-generation: 0.2.10-0trusty
    ...
    14:15:01  ---> fe19c151741d
    14:15:01 Removing intermediate container 6391121c452d
    14:15:01 Step 24 : RUN echo "ros-indigo-openrtm-aist: 1.1.0-25trusty" && python3 -u /tmp/wrapper_scripts/apt-get.py update-and-install -q -y ros-indigo-openrtm-aist
    14:15:02  ---> Running in 91aefaee0645
    14:15:02 time="2015-02-07T22:15:02Z" level="info" msg="open /var/lib/docker/containers/91aefaee06458d1ffb797b37825832564e3bdc0902197254f94ef5190fa5dbba/resolv.conf: no such file or directory" 
    14:15:02 Build step 'Execute shell' marked build as failure

The corresponding output from the cleanup log file:

    2015-02-07 22:15:02,082 removing container 91aefaee0645
    2015-02-07 22:15:02,226 successfully removed container: 91aefaee0645

**Comment by dirk-thomas** [comment]
Similar to #40 but on a container level rather then on images.

**Comment by tfoote** [comment]
fixed in #45
