### ISSUE TITLE
clean up still interfering with builds

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/buildfarm_deployment#46]
Folluw up of #43 and #40. It looks like that the latest builds are still failing: http://54.183.26.131:8080/job/Jbin_uT32__tf2_ros__ubuntu_trusty_i386__binary/3/consoleFull

I logged into the slave but couldn't find any hashes in the log file matching the errors in the console output, e.g.:

    Error removing intermediate container bed26c5d4211: The given container is <nil>

But it looks like there are still multiple cron jobs deleting docker stuff:

    # HEADER: This file was autogenerated at 2015-02-03 00:30:17 +0000 by puppet.
    # HEADER: While it can still be managed manually, it is definitely not recommended.
    # HEADER: Note particularly that the comments starting with 'Puppet Name' should
    # HEADER: not be deleted, as doing so could cause duplicate cron jobs.
    # Puppet Name: docker_cleanup_images
    15 */2 * * * bash -c "python3 -u /home/jenkins-slave/cleanup_docker_images.py"
    # Puppet Name: docker_cleanup_containers
    5 */2 * * * bash -c "docker ps -aq | xargs -L1 docker rm "

**Comment by dirk-thomas** [comment]
It also looks like that the cleanup log file does not contain any output for the last 17h.

**Comment by dirk-thomas** [comment]
Trying to run the cleanup script manually on one of the slaves:

    Traceback (most recent call last):
      File "/home/jenkins-slave/cleanup_docker_images.py", line 4, in <module>
        import dateutil.parser
    ImportError: No module named 'dateutil'

**Comment by dirk-thomas** [comment]
Did you also resolved the duplicate cronjobs?

**Comment by tfoote** [comment]
Yeah, in the 1st commit,  495d802. The ensure absent was there, but it didn't specify the user, and the default was 'root' not 'jenkins-slave' https://github.com/ros-infrastructure/buildfarm_deployment/commit/495d802186d426a922aaf999d1dffa5af944374a#diff-a2052a49729c2f5f50ebbc65e3d02352R163

I also added the cleanup rule for the repo. The job does not exist on the master so I didn't add a cleanup for it.

**Comment by tfoote** [comment]
Also, since the last run, I verified the cronjob has gone away:

```
# HEADER: This file was autogenerated at 2015-02-16 23:30:11 +0000 by puppet.
# HEADER: While it can still be managed manually, it is definitely not recommended.
# HEADER: Note particularly that the comments starting with 'Puppet Name' should
# HEADER: not be deleted, as doing so could cause duplicate cron jobs.
# Puppet Name: docker_cleanup_images
15 */2 * * * bash -c "python3 -u /home/jenkins-slave/cleanup_docker_images.py"
```

**Comment by dirk-thomas** [comment]
This seems to happen again:

* http://54.183.26.131:8080/job/Ibin_uS32__controller_manager__ubuntu_saucy_i386__binary/2/
* http://54.183.26.131:8080/job/Ibin_uS32__forward_command_controller__ubuntu_saucy_i386__binary/2/
* http://54.183.26.131:8080/job/Ibin_uS32__cob_default_robot_config__ubuntu_saucy_i386__binary/2/
