### ISSUE TITLE
docker cleanup issues

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/buildfarm_deployment#50]
The list of currently known issues is:

* [x] the current state of the cleanup script still interferes with the builds: https://github.com/ros-infrastructure/buildfarm_deployment/issues/46#issuecomment-75383634
* [x] cleaning up until 50% disk space is free is wasting valuable resources on the slave
* [ ] the disk cleanup is slower in freeing disk space than new data is generated while the farm is busy (which disables slaves regularly - but that should only be the exception)
* [ ] ~~the cleanup script is trying to remove base images which is not desired~~
* [x] does not terminate cleanly: https://github.com/ros-infrastructure/buildfarm_deployment/issues/50#issuecomment-75385359

This ticket should stay open until any remaining issues related to the docker cleanup script have been resolved. One use case which should work before closing this ticket is to perform a series of full rebuilds on the farm:
* without any jobs failing due to docker cleanup related issues as well as
* the farm running continuously without having to disable slaves due to running low on disk space.

**Comment by dirk-thomas** [comment]
Non graceful termination:

    2015-02-21 02:15:01,616 Disk space satified ending
    2015-02-21 02:15:01,617 Uncaught exception in cleanup_docker_image.py: Traceback (most recent call last):
      File "/home/jenkins-slave/cleanup_docker_images.py", line 173, in <module>
        main()
      File "/home/jenkins-slave/cleanup_docker_images.py", line 153, in main
        sys.exit(0)
    SystemExit: 0

**Comment by tfoote** [comment]
Clean termination: 13d1e9d979923be444ffdb0082184646773817d4
Better usage of disk space on larger disks: 04e69e5151304cfe2e76ced2d6da2007e88c51c9

I believe the old images had retained cron jobs. I've rolled over all the old executors.

**Comment by tfoote** [comment]
The base images will be cleaned up only if there are no containers using them. And if we go the full timeout and nothing is using them It's probably ok to clean them. They are only ~ 100 Mb to redownload and explicitly listing anything is just another thing to maintiain adding complexity and overhead. I think whitelisting the base images or something like that would be an overoptimization. In practice we will likely never be that idle and they'll be protected by the active containers.

**Comment by tfoote** [comment]
Filed slow rmi upstream: https://github.com/docker/docker/issues/11053
