### ISSUE TITLE
Improve documentation about ssh keys

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/buildfarm_deployment#58]
Based on the recent question on the mailing list: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ros-sig-buildfarm/P32OdoGFYkg/awEAi8Bx4jgJ

The description of the `ssh_keys` for all three machine types is pretty confusing.
I would recommend something like this:

```
 * Configure as many public ssh keys as you want for administrators to log in.
 * On the repo machine make sure there is public ssh key which matches the private ssh key `jenkins::private_ssh_key` provisioned on the master.
```

The key `jenkins-slave::authorized_keys` described for the repo machine seems to not exist in the config repository.
Is this a private ssh key? If so the documentation should state that explicitly.

Also the indentation of the configuration option for the repo machine seem to be wrong.

**Comment by tfoote** [comment]
cleaned up based on comments

**Comment by dirk-thomas** [comment]
Thanks!
