### ISSUE TITLE
Incompatibility with tracywebtech-pip v1.3.4

### ISSUE THREAD

**Issue by ipa-mdl** [ros-infrastructure/buildfarm_deployment#65]
Running reconfgure.bash master | slave | repo results in (from /var/log/puppet.log):
````
Could not find dependency Exec[install-pip3] for Exec[install-docker-py]
at /root/buildfarm_deployment/slave/modules/pip/manifests/install.pp:33
````
I tracked this error back to https://github.com/TracyWebTech/puppet-pip/pull/5

It works if I freeze tracywebtech-pip to version 1.3.2 in Puppetfile:
```
mod 'tracywebtech-pip', '1.3.2'
```
Another solution would be to provide Exec[install-pip3] with checks for pip3, perhaps using pip::installation.

**Comment by tfoote** [comment]
Sounds like they've just upgraded. I'll check this when I'm back in the office next wee.
