### ISSUE TITLE
Make puppet more verbose on errors

### ISSUE THREAD

**Issue by dejanpan** [ros-infrastructure/buildfarm_deployment#67]
Currently when running ```./reconfigure.bash machine``` this script just exits silently even though puppet error-red. To verify that puppet installed correctly one needs to examine "/var/log/puppet.log" currently.
The proposal would be to propagate puppet error messages to the wrapper bash script or to clearly signal an error and point the user to examine the "/var/log/puppet.log" file.

**Comment by ipa-mdl** [comment]
+1
If you don't want to print all output, at least the puppet exit code should be checked, e.g.
```
puppet ... || { r=$?; echo "puppet failed, please check /var/log/puppet.log"; exit $r; }
```
