### ISSUE TITLE
remove python-catkintools from bootstrap repo

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/buildfarm_deployment#99]
There is also `python-catkin-tools` which is the desired one.

**Comment by tfoote** [comment]
Cleared from boostrap repo

**Comment by dirk-thomas** [comment]
Do the remaining incarnations of this package get removed automatically from the other repos or do you have to remove them manually too?

**Comment by tfoote** [comment]
if they don't get invalidated it's manual

**Comment by dirk-thomas** [comment]
Then please take care of the left over packages. I will reopen this.

**Comment by tfoote** [comment]
removed from ros_bootstrap, all repositories.ros.org and repos.ros.org for good measure
